### ISSUE TITLE
Strange Sizing Output

### ISSUE THREAD

**Issue by thebioengineer** [javierluraschi/nomnoml#4] opened 2019-07-08 03:12 UTC
somewhat related to issue #2 , but I am getting a strange size issue in my rmd output viewer when I render the html. If I reopen the html file it looks fine. I am running the stable cran version:

---
title: "Untitled"
author: "Ellis Hughes"
date: "July 5, 2019"
output: html_document
---

```{r eval=TRUE,fig.width=5, fig.height=5}

nomnoml::nomnoml("
[Model]->[Action]
[Action]->[Game/Simulation]
[Game/Simulation]->[reward]
[Game/Simulation]->[state]
[reward]->[Model]
[state]->[Model]
")

```

```{r session_info}
sessionInfo()
```
![image](https://user-images.githubusercontent.com/22481467/60780477-757af400-a0f3-11e9-84d5-d873cfbd92f8.png)

session info:
```r
sessionInfo()
## R version 3.5.1 (2018-07-02)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 17763)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
##  [1] htmlwidgets_1.3 compiler_3.5.1  magrittr_1.5    tools_3.5.1    
##  [5] htmltools_0.3.6 yaml_2.2.0      Rcpp_1.0.0      nomnoml_0.1.0  
##  [9] stringi_1.2.4   rmarkdown_1.13  knitr_1.23      jsonlite_1.5   
## [13] stringr_1.3.1   xfun_0.8        digest_0.6.18   evaluate_0.14
```

**Comment by andrie** [comment] 2020-12-09 13:39
I'm not able to reproduce this. I notice you opened the issue quite some time ago.  Do you still experience the same issue?

**Comment by andrie** [comment] 2020-12-11 09:00
Closing because I haven't been able to replicate.

**Closed as completed by andrie** 2020-12-11 09:00 UTC

**Comment by thebioengineer** [comment] 2020-12-11 16:11
Looks like it is working now. Thanks. Not sure what caused this, but its resolved 🤷
